src/Iris.Web/Areas/Admin/Controllers/CommentController.cs
using System.Collections.Generic;
using Iris.Datalayer.Context;
using Iris.DomainClasses.Entities;
using Iris.Model.AdminModel;
using Iris.Servicelayer.EFServices.Enums;
using Iris.Servicelayer.Interfaces;
using Iris.Web.Filters;
using Iris.Web.Helpers;
using Iris.Web.HtmlCleaner;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Iris.Web.Areas.Admin.Controllers
{
    [SiteAuthorize(Roles = "admin,moderator")]
    [Area("Admin")]
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;
        private readonly IUnitOfWork _uow;

        public CommentController(IUnitOfWork uow, ICommentService commentService)
        {
            _uow = uow;
            _commentService = commentService;
        }

        public virtual ActionResult Index()
        {
            return PartialView("_Index");
        }

        public virtual ActionResult DataTable(string term = "", int page = 0, int count = 10,
            Order order = Order.Descending, CommentOrderBy orderBy = CommentOrderBy.AddDate,
            CommentSearchBy searchBy = CommentSearchBy.UserName)
        {
            ViewBag.CurrentPage = page;
            ViewBag.Count = count;


            ViewBag.TERM = term;
            ViewBag.PAGE = page;
            ViewBag.COUNT = count;
            ViewBag.ORDER = order;
            ViewBag.ORDERBY = orderBy;
            ViewBag.SEARCHBY = searchBy;

            ViewBag.OrderByList = DropDownList.OrderList(order);
            ViewBag.CountList = DropDownList.CountList(count);

            var selectListOrderBy = new List<SelectListItem>
            {
                new SelectListItem {Value = "AddDate", Text = "تاریخ ارسال"},
                new SelectListItem {Value = "IsApproved", Text = "وضعیت"},
                new SelectListItem {Value = "LikeCount", Text = "رای ها"},
                new SelectListItem {Value = "UserName", Text = "نام کاربری"},
                new SelectListItem {Value = "Author", Text = "نویسنده"},
                new SelectListItem {Value = "IP", Text = "IP"}
            };

            ViewBag.OrderByItems = new SelectList(selectListOrderBy, "Value", "Text", orderBy);


            IList<CommentDataTableModel> model = _commentService.GetDataTable(term, page, count, order, orderBy,
                searchBy);


            ViewBag.TotalRecords = (string.IsNullOrEmpty(term)) ? _commentService.Count : model.Count;


            foreach (CommentDataTableModel item in model)
            {
                item.AvatarPath = Url.Content("~/Content/Images/user.gif");
            }

            return PartialView("_DataTable", model);
        }

        [HttpGet]
        public virtual ActionResult ConfirmDelete(int id)
        {
            ViewBag.Id = id;
            return PartialView("_ConfirmDelete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Delete(int id)
        {
            _commentService.Remove(id);
            _uow.SaveChanges();
            return PartialView("_Alert", new Alert
            {
                Message = "دیدگاه مورد نظر با موفقیت حذف شد",
                Mode = AlertMode.Success
            });
        }

        [HttpGet]
        public virtual ActionResult Edit(int id)
        {
            Comment selectedComment = _commentService.GetComment(id);
            return PartialView("_Edit", new EditCommentModel
            {
                Id = selectedComment.Id,
                Body = selectedComment.Body
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Edit(EditCommentModel commentModel)
        {
            _commentService.Update(new Comment { Id = commentModel.Id, Body = commentModel.Body.ToSafeHtml() });
            _uow.SaveChanges();
            return PartialView("_Alert", new Alert
            {
                Message = "دیدگاه مورد نظر با موفقیت به روز رسانی شد",
                Mode = AlertMode.Success
            });
        }

        [HttpGet]
        public virtual ActionResult Approve(int id)
        {
            _commentService.Approve(id);
            _uow.SaveChanges();
            return RenderApproveButtons(id, "disapproved");
        }

        [HttpGet]
        public virtual ActionResult DisApprove(int id)
        {
            _commentService.DisApprove(id);
            _uow.SaveChanges();
            return RenderApproveButtons(id, "approved");
        }

        public virtual ActionResult RenderApproveButtons(int id, string type)
        {
            return ViewComponent("ApproveButtons", new {id, type});
        }

        public virtual ActionResult AutoCompleteSearch(string term, CommentSearchBy searchBy = CommentSearchBy.Body)
        {
            return new EmptyResult();
        }
    }

    public class ApproveButtonsViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(int id, string type)
        {
            ViewBag.Id = id;
            ViewBag.Status = (type == "approved") ? "approved" : "disapproved";
            return View("_ApproveStatusButton");
        }
    }
}

src/Iris.Web/Controllers/ArticleController.cs
using System.Collections.Generic;
using Iris.Datalayer.Context;
using Iris.Model;
using Iris.Servicelayer.Interfaces;
using Iris.Utilities;
using Iris.Web.Filters;
using Microsoft.AspNetCore.Mvc;

namespace Iris.Web.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly IUnitOfWork _uow;
        private readonly IUserService _userService;

        public ArticleController(IUnitOfWork uow, IUserService userService, IArticleService articleService)
        {
            _uow = uow;
            _userService = userService;
            _articleService = articleService;
        }

        public virtual ActionResult Index(int id)
        {
            var model = _articleService.Find(id);
            if (model == null)
            {
                return NotFound();
            }

            _articleService.IncrementVisitedCount(id);

            return View(model);
        }

        [SiteAuthorize]
        [HttpPost("article/like/{id}")]

        public virtual ActionResult Like([FromRoute] int id)
        {
            string result;
            int likeCount = 0;
            if (!_articleService.IsUserLikeArticle(id, User.Identity.Name))
            {
                likeCount = _articleService.Like(id, _userService.Find(User.Identity.Name));
                _uow.SaveChanges();
                result = "success";
            }
            else
            {
                result = "duplicate";
            }

            return Json(new { result, count = ConvertToPersian.ConvertToPersianString(likeCount) });
        }

        [SiteAuthorize]
        [HttpPost("article/dislike/{id}")]
        public virtual ActionResult DisLike([FromRoute] int id)
        {
            string result;
            int likeCount = 0;
            if (!_articleService.IsUserLikeArticle(id, User.Identity.Name))
            {
                likeCount = _articleService.DisLike(id, _userService.Find(User.Identity.Name));
                _uow.SaveChanges();
                result = "success";
            }
            else
            {
                result = "duplicate";
            }

            return Json(new { result, count = ConvertToPersian.ConvertToPersianString(likeCount) });
        }

        public virtual ActionResult UserArticles(string userName, int page = 0, int count = 100)
        {
            if (string.IsNullOrEmpty(userName)) userName = User.Identity.Name;
            IList<PostDetailModel> model = _articleService.GetUserArticles(userName, page, count);
            ViewBag.UserName = userName;
            return PartialView("_UserArticles", model);
        }

        public virtual ActionResult UserArticlesList(string userName)
        {
            ViewBag.UserName = userName;
            return View();
        }
    }
}

src/Iris.Web/Controllers/PageController.cs
using Iris.Datalayer.Context;
using Iris.Servicelayer.Interfaces;
using Iris.Utilities;
using Iris.Web.Filters;
using Microsoft.AspNetCore.Mvc;

namespace Iris.Web.Controllers
{
    public class PageController : Controller
    {
        private readonly IPageService _pageService;
        private readonly IUnitOfWork _uow;
        private readonly IUserService _userService;

        public PageController(IUnitOfWork uow, IUserService userService, IPageService pageService)
        {
            _uow = uow;
            _userService = userService;
            _pageService = pageService;
        }

        public virtual ActionResult Index(int id)
        {
            var model = _pageService.Get(id);

            if (model == null)
            {
                return NotFound();
            }

            _pageService.IncrementVisitedCount(id);

            return View(model);
        }

        [SiteAuthorize]
        [HttpPost("page/like/{id}")]
        public virtual ActionResult Like([FromRoute] int id)
        {
            string result;
            int likeCount = 0;
            if (!_pageService.IsUserLikePage(id, User.Identity.Name))
            {
                likeCount = _pageService.Like(id, _userService.Find(User.Identity.Name));
                _uow.SaveChanges();
                result = "success";
            }
            else
            {
                result = "duplicate";
            }

            return Json(new { result, count = ConvertToPersian.ConvertToPersianString(likeCount) });
        }

        [SiteAuthorize]
        [HttpPost("page/dislike/{id}")]
        public virtual ActionResult DisLike([FromRoute] int id)
        {
            string result;
            int likeCount = 0;
            if (!_pageService.IsUserLikePage(id, User.Identity.Name))
            {
                likeCount = _pageService.DisLike(id, _userService.Find(User.Identity.Name));
                _uow.SaveChanges();
                result = "success";
            }
            else
            {
                result = "duplicate";
            }

            return Json(new { result, count = ConvertToPersian.ConvertToPersianString(likeCount) });
        }
    }
}

src/Iris.Web/Controllers/PostController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using DNTPersianUtils.Core;
using Iris.Datalayer.Context;
using Iris.DomainClasses.Entities;
using Iris.Model;
using Iris.Servicelayer.Interfaces;
using Iris.Utilities;
using Iris.Web.Filters;
using Microsoft.AspNetCore.Mvc;

namespace Iris.Web.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _postService;
        private readonly IUnitOfWork _uow;
        private readonly IUserService _userService;
        private readonly IBookSearch _bookSearch;

        public PostController(
            IUnitOfWork uow,
            IPostService postService,
            IUserService userService,
            IBookSearch bookSearch
        )
        {
            _uow = uow;
            _postService = postService;
            _userService = userService;
            _bookSearch = bookSearch;
        }

        [Route("post/index/{id:int}/{title?}")]
        public virtual ActionResult Index(int id)
        {
            var post = _postService.GetPost(id);

            if (post == null)
            {
                return NotFound();
            }

            _postService.IncrementVisitedNumber(id);

            return View(post);
        }

        [SiteAuthorize]
        [HttpPost("post/like/{id}")]
        public virtual ActionResult Like([FromRoute] int id)
        {
            string result;
            int likeCount = 0;
            if (!_postService.IsUserLikePost(id, User.Identity.Name))
            {
                likeCount = _postService.Like(id, _userService.Find(User.Identity.Name));
                _uow.SaveChanges();
                result = "success";
            }
            else
            {
                result = "duplicate";
            }

            return Json(new { result, count = ConvertToPersian.ConvertToPersianString(likeCount) });
        }

        [SiteAuthorize]
        [HttpPost("post/dislike/{id}")]
        public virtual ActionResult DisLike([FromRoute] int id)
        {
            string result;
            int likeCount = 0;
            if (!_postService.IsUserLikePost(id, User.Identity.Name))
            {
                likeCount = _postService.DisLike(id, _userService.Find(User.Identity.Name));
                _uow.SaveChanges();
                result = "success";
            }
            else
            {
                result = "duplicate";
            }

            return Json(new { result, count = ConvertToPersian.ConvertToPersianString(likeCount) });
        }

        [HttpPost("post/links")]
        public async Task<ActionResult> GetDownloadLinks(
            [FromBody] GetDownloadLinksModel model,
            CancellationToken cancellationToken
        )
        {
            if (model.Answer.Trim().ApplyCorrectYeKe() != "طهران")
            {
                return NotFound();
            }

            return PartialView("_DownloadLinks", await _postService.GetDownloadLinks(model.PostId, cancellationToken));
        }

        public virtual ActionResult SilmilarPosts(int id)
        {
            IEnumerable<MorePostsLikeThis> model = _bookSearch.GetMoreLikeThisPostItems(id);
            return PartialView("_SimilarPosts", model);
        }

        public virtual ActionResult UserPosts(string userName, int page = 0, int count = 100)
        {
            if (string.IsNullOrEmpty(userName)) userName = User.Identity.Name;

            IList<PostDetailModel> model = _postService.GetUserPosts(userName, page, count);
            ViewBag.UserName = userName;
            return PartialView("_UserPosts", model);
        }

        public virtual ActionResult UserPostsList(string userName)
        {
            ViewBag.UserName = userName;
            return View();
        }
    }

    public class GetDownloadLinksModel
    {
        public int PostId { get; set; }
        public string Answer { get; set; }
    }
}

src/Iris.Web/Views/Comment/_AddAnonymousArticleComment.cshtml
@model Iris.Model.AddAnonymousCommentModel

<div class="comment-reply" id="commentReply">
    <!-- begin commnet-erply div -->
    @using (Html.AjaxBeginForm("AddAnonymousArticleComment", "Comment", new AjaxOptions { HttpMethod = "POST", OnSuccess = "AddComment.onSuccess", LoadingElementDuration = 300, LoadingElementId = "loadingMessage" }, new { @class = "form-horizontal", id = "frmCommentReply" }))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("id", ViewBag.PageId as string)
        @Html.Hidden("replyId", ViewBag.ReplyId as string)
        <div class="control-group">
            <label class="control-label" style="width: 10px;" for="Body">متن</label>
            <div class="controls" style="margin-right: 70px; text-align: right;">
                @Html.TextAreaFor(comment => comment.Body, new { cols = "10", placeholder = "دیدگاه خود را بنویسید..." })
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="Email">ایمیل</label>
            <div class="pull-right">
                @Html.TextBoxFor(comment => comment.Email, new { placeholder = "Email", @class = "ltr" })
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="Name">نام</label>
            <div class="pull-right">
                @Html.TextBoxFor(comment => comment.Name, new { placeholder = "نام" })
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="Captcha">انسان یاب!</label>
            <div style="margin-right: 20px;">
                <dnt-captcha asp-captcha-generator-max="9000"
                             asp-captcha-generator-min="1"
                             asp-captcha-generator-language="English"
                             asp-captcha-generator-display-mode="SumOfTwoNumbers"
                             asp-use-relative-urls="true"
                             asp-placeholder="جواب"
                             asp-validation-error-message="پاسخ صحیح را وارد نمایید"
                             asp-font-name="Tahoma"
                             asp-font-size="20"
                             asp-fore-color="#333333"
                             asp-back-color="#ccc"
                             asp-text-box-class="text-box single-line form-control col-md-4"
                             asp-text-box-template="<div class='input-group span-4' style='margin-right:0;'><span class='input-group-addon'></span>{0}</div>"
                             asp-validation-message-class="text-danger"
                             asp-refresh-button-class="icon-refresh btn-sm"
                             asp-use-noise="false" />
            </div>
        </div>
        <div class="clear"></div>
        <div style="display: none" id="loading1">
            <img src="~/Content/Images/loading1.gif" />
        </div>
        <div style="margin-right: 20px; margin-bottom: 10px; margin-top: 10px;">
            <button type="submit" class="btn btn-primary" style="margin-right: 50px;">ارسال</button>
        </div>
        <div id="addCommentResult">@Html.ValidationSummary()</div>
    }
    <div class="clear"></div>
</div>
<!-- end comment-reply -->

src/Iris.Web/Views/Comment/_AddAnonymousPageComment.cshtml
@model Iris.Model.AddAnonymousCommentModel

<div class="comment-reply" id="commentReply">
    <!-- begin commnet-erply div -->
    @using (Html.AjaxBeginForm("AddAnonymousPageComment", "Comment", new AjaxOptions { HttpMethod = "POST", OnSuccess = "AddComment.onSuccess", LoadingElementDuration = 300, LoadingElementId = "loadingMessage" }, new { @class = "form-horizontal", id = "frmCommentReply" }))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("id", ViewBag.PageId as string)
        @Html.Hidden("replyId", ViewBag.ReplyId as string)
        <div class="control-group">
            <label class="control-label" style="width: 10px;" for="Body">متن</label>
            <div class="controls" style="margin-right: 70px; text-align: right;">
                @Html.TextAreaFor(comment => comment.Body, new { cols = "10", placeholder = "دیدگاه خود را بنویسید..." })
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="Email">ایمیل</label>
            <div class="pull-right">
                @Html.TextBoxFor(comment => comment.Email, new { placeholder = "Email", @class = "ltr" })
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="Name">نام</label>
            <div class="pull-right">
                @Html.TextBoxFor(comment => comment.Name, new { placeholder = "نام" })
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="Captcha">انسان یاب!</label>
            <div style="margin-right: 20px;">
                <dnt-captcha asp-captcha-generator-max="9000"
                             asp-captcha-generator-min="1"
                             asp-captcha-generator-language="English"
                             asp-captcha-generator-display-mode="SumOfTwoNumbers"
                             asp-use-relative-urls="true"
                             asp-placeholder="جواب"
                             asp-validation-error-message="پاسخ صحیح را وارد نمایید"
                             asp-font-name="Tahoma"
                             asp-font-size="20"
                             asp-fore-color="#333333"
                             asp-back-color="#ccc"
                             asp-text-box-class="text-box single-line form-control col-md-4"
                             asp-text-box-template="<div class='input-group span-4' style='margin-right:0;'><span class='input-group-addon'></span>{0}</div>"
                             asp-validation-message-class="text-danger"
                             asp-refresh-button-class="icon-refresh btn-sm"
                             asp-use-noise="false" />
            </div>
        </div>
        <div class="clear"></div>
        <div style="display: none" id="loading1">
            <img src="~/Content/Images/loading1.gif" />
        </div>
        <div style="margin-right: 20px; margin-bottom: 10px; margin-top: 10px;">
            <button type="submit" class="btn btn-primary" style="margin-right: 50px;">ارسال</button>
        </div>
        <div id="addCommentResult">@Html.ValidationSummary()</div>
    }
    <div class="clear"></div>
</div>
<!-- end comment-reply -->

src/Iris.Web/Views/Comment/_ArticleUserComments.cshtml
@model IEnumerable<Iris.Model.ArticleCommentDetailModel>
@{
    int currentPage = ViewBag.CurrentPage + 1;
    int count = ViewBag.Count;
    int max = (ViewBag.TotalRecords % count == 0) ? ViewBag.TotalRecords / count : (ViewBag.TotalRecords / count) + 1;
    const int size = 8;
    var firstPage = ((currentPage - size) <= 0) ? 0 : currentPage - size;
    var lastPage = ((currentPage + size) >= max) ? max : currentPage + size;
}
<div style="text-align: right;">
    @foreach (var comment in Model)
    {
        <div style="margin: 20px;">
            <div>@Html.ActionLink(comment.Title, "Index", "Article", new { id = comment.ArticleId, title = Html.ResolveTitleForUrl(comment.Title) }, null)
            </div>
            <div>
                @Html.Raw(comment.Body)
            </div>
            <div>
                <span class="label label-info"><span class="unicode">@Html.ConvertToPersianString(comment.LikeCount)</span> امتیاز</span>
                <span class="label label-important"><span class="unicode">@Html.ConvertToPersianDateTime(comment.AddedDate, "D,H")</span></span>
            </div>
        </div>
    }

    <!-- begin page navigation section -->
    <div class="pagination pagination-centered">
        <ul>
            @if (currentPage - 1 == firstPage)
            {
                <li class="active"><a>ابتدا</a></li>
            }
            else
            {
                <li>@Html.AjaxActionLink("ابتدا", "ArticleUserComments", "Comment", new { page = 0, count = ViewBag.Count }, new AjaxOptions { HttpMethod = "Get", InsertionMode = InsertionMode.Replace, UpdateTargetId = "userArticleComments", OnSuccess = "Book.onSuccess", OnBegin = "Book.onBegin" }, null)
                </li>
            }
            @for (var i = firstPage; i < lastPage; i++)
            {
                if (i + 1 == currentPage)
                {
                <li class="active"><a>@Html.ConvertToPersianString(i + 1)</a></li>
                }
                else
                {
                <li>@Html.AjaxActionLink(Html.ConvertToPersianString(i + 1).ToString(), "ArticleUserComments", "Comment", new { page = i, count = ViewBag.Count }, new AjaxOptions { HttpMethod = "Get", InsertionMode = InsertionMode.Replace, UpdateTargetId = "userArticleComments", OnSuccess = "Book.onSuccess", OnBegin = "Book.onBegin" }, null)
                </li>
                }
            }
            @if (currentPage == lastPage)
            {
                <li class="active"><a>انتها</a></li>
            }
            else
            {
                <li>@Html.AjaxActionLink("انتها", "ArticleUserComments", "Comment", new { page = lastPage - 1, count = ViewBag.Count }, new AjaxOptions { HttpMethod = "Get", InsertionMode = InsertionMode.Replace, UpdateTargetId = "userArticleComments", OnSuccess = "Book.onSuccess", OnBegin = "Book.onBegin" }, null)
                </li>
            }
        </ul>
    </div>
    <!-- end page navigation section -->
</div>

src/Iris.Web/Views/Comment/_CommentClosed.cshtml
<div style="text-align: center;margin:10px;">
    <div class="alert alert-error" style="text-align: right; width: 70%; margin: 0 auto;">
        <button type="button" class="close" data-dismiss="alert">×</button>
        ارسال دیدگاه برای این موضوع بسته شده است!
    </div>
</div>

src/Iris.Web/Views/Comment/_PageUserComments.cshtml
@model IEnumerable<Iris.Model.PageCommentDetailModel>
@{
    int currentPage = ViewBag.CurrentPage + 1;
    int count = ViewBag.Count;
    int max = (ViewBag.TotalRecords % count == 0) ? ViewBag.TotalRecords / count : (ViewBag.TotalRecords / count) + 1;
    const int size = 8;
    var firstPage = ((currentPage - size) <= 0) ? 0 : currentPage - size;
    var lastPage = ((currentPage + size) >= max) ? max : currentPage + size;
}
<div style="text-align: right;">
    @foreach (var comment in Model)
    {
        <div style="margin: 20px;">
            <div>@Html.ActionLink(comment.Title, "Index", "Page", new { id = comment.PageId, title = Html.ResolveTitleForUrl(comment.Title) }, null)
            </div>
            <div>
                @Html.Raw(comment.Body)
            </div>
            <div>
                <span class="label label-info"><span class="unicode">@Html.ConvertToPersianString(comment.LikeCount)</span> امتیاز</span>
                <span class="label label-important"><span class="unicode">@Html.ConvertToPersianDateTime(comment.AddedDate, "D,H")</span></span>
            </div>
        </div>
    }

    <!-- begin page navigation section -->
    <div class="pagination pagination-centered">
        <ul>
            @if (currentPage - 1 == firstPage)
            {
                <li class="active"><a>ابتدا</a></li>
            }
            else
            {
                <li>@Html.AjaxActionLink("ابتدا", "PageUserComments", "Comment", new { page = 0, count = ViewBag.Count }, new AjaxOptions { HttpMethod = "Get", InsertionMode = InsertionMode.Replace, UpdateTargetId = "userPageComments", OnSuccess = "Book.onSuccess", OnBegin = "Book.onBegin" }, null)
                </li>
            }
            @for (var i = firstPage; i < lastPage; i++)
            {
                if (i + 1 == currentPage)
                {
                <li class="active"><a>@Html.ConvertToPersianString(i + 1)</a></li>
                }
                else
                {
                <li>@Html.AjaxActionLink(Html.ConvertToPersianString(i + 1).ToString(), "PageUserComments", "Comment", new { page = i, count = ViewBag.Count }, new AjaxOptions { HttpMethod = "Get", InsertionMode = InsertionMode.Replace, UpdateTargetId = "userPageComments", OnSuccess = "Book.onSuccess", OnBegin = "Book.onBegin" }, null)
                </li>
                }
            }
            @if (currentPage == lastPage)
            {
                <li class="active"><a>انتها</a></li>
            }
            else
            {
                <li>@Html.AjaxActionLink("انتها", "PageUserComments", "Comment", new { page = lastPage - 1, count = ViewBag.Count }, new AjaxOptions { HttpMethod = "Get", InsertionMode = InsertionMode.Replace, UpdateTargetId = "userPageComments", OnSuccess = "Book.onSuccess", OnBegin = "Book.onBegin" }, null)
                </li>
            }
        </ul>
    </div>
    <!-- end page navigation section -->
</div>

src/Iris.Web/Views/Comment/_PostUserComments.cshtml
@model IEnumerable<Iris.Model.PostCommentDetailModel>
@{
    int currentPage = ViewBag.CurrentPage + 1;
    int count = ViewBag.Count;
    int max = (ViewBag.TotalRecords % count == 0) ? ViewBag.TotalRecords / count : (ViewBag.TotalRecords / count) + 1;
    const int size = 8;
    var firstPage = ((currentPage - size) <= 0) ? 0 : currentPage - size;
    var lastPage = ((currentPage + size) >= max) ? max : currentPage + size;
}
<div style="text-align: right;">
    @foreach (var comment in Model)
    {
        <div style="margin: 20px;">
            <div>@Html.ActionLink(comment.Title, "Index", "Post", new { id = comment.PostId, title = Html.ResolveTitleForUrl(comment.Title) }, null)
            </div>
            <div>
                @Html.Raw(comment.Body)
            </div>
            <div>
                <span class="label label-info"><span class="unicode">@Html.ConvertToPersianString(comment.LikeCount)</span> امتیاز</span>
                <span class="label label-important"><span class="unicode">@Html.ConvertToPersianDateTime(comment.AddedDate, "D,H")</span></span>
            </div>
        </div>
    }

    <!-- begin page navigation section -->
    <div class="pagination pagination-centered">
        <ul>
            @if (currentPage - 1 == firstPage)
            {
                <li class="active"><a>ابتدا</a></li>
            }
            else
            {
                <li>@Html.AjaxActionLink("ابتدا", "PostUserComments", "Comment", new { page = 0, count = ViewBag.Count }, new AjaxOptions { HttpMethod = "Get", InsertionMode = InsertionMode.Replace, UpdateTargetId = "userPostComments", OnSuccess = "Book.onSuccess", OnBegin = "Book.onBegin" }, null)
                </li>
            }
            @for (var i = firstPage; i < lastPage; i++)
            {
                if (i + 1 == currentPage)
                {
                <li class="active"><a>@Html.ConvertToPersianString(i + 1)</a></li>
                }
                else
                {
                <li>@Html.AjaxActionLink(Html.ConvertToPersianString(i + 1).ToString(), "PostUserComments", "Comment", new { page = i, count = ViewBag.Count }, new AjaxOptions { HttpMethod = "Get", InsertionMode = InsertionMode.Replace, UpdateTargetId = "userPostComments", OnSuccess = "Book.onSuccess", OnBegin = "Book.onBegin" }, null)
                </li>
                }
            }
            @if (currentPage == lastPage)
            {
                <li class="active"><a>انتها</a></li>
            }
            else
            {
                <li>@Html.AjaxActionLink("انتها", "PostUserComments", "Comment", new { page = lastPage - 1, count = ViewBag.Count }, new AjaxOptions { HttpMethod = "Get", InsertionMode = InsertionMode.Replace, UpdateTargetId = "userPostComments", OnSuccess = "Book.onSuccess", OnBegin = "Book.onBegin" }, null)
                </li>
            }
        </ul>
    </div>
    <!-- end page navigation section -->
</div>