src/Iris.Web/Areas/Admin/Controllers/CommentController.cs
using System.Collections.Generic;
using Iris.Datalayer.Context;
using Iris.DomainClasses.Entities;
using Iris.Model.AdminModel;
using Iris.Servicelayer.EFServices.Enums;
using Iris.Servicelayer.Interfaces;
using Iris.Web.Filters;
using Iris.Web.Helpers;
using Iris.Web.HtmlCleaner;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Iris.Web.Areas.Admin.Controllers
{
    [SiteAuthorize(Roles = "admin,moderator")]
    [Area("Admin")]
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;
        private readonly IUnitOfWork _uow;

        public CommentController(IUnitOfWork uow, ICommentService commentService)
        {
            _uow = uow;
            _commentService = commentService;
        }

        public virtual ActionResult Index()
        {
            return PartialView("_Index");
        }

        public virtual ActionResult DataTable(string term = "", int page = 0, int count = 10,
            Order order = Order.Descending, CommentOrderBy orderBy = CommentOrderBy.AddDate,
            CommentSearchBy searchBy = CommentSearchBy.UserName)
        {
            ViewBag.CurrentPage = page;
            ViewBag.Count = count;


            ViewBag.TERM = term;
            ViewBag.PAGE = page;
            ViewBag.COUNT = count;
            ViewBag.ORDER = order;
            ViewBag.ORDERBY = orderBy;
            ViewBag.SEARCHBY = searchBy;

            ViewBag.OrderByList = DropDownList.OrderList(order);
            ViewBag.CountList = DropDownList.CountList(count);

            var selectListOrderBy = new List<SelectListItem>
            {
                new SelectListItem {Value = "AddDate", Text = "تاریخ ارسال"},
                new SelectListItem {Value = "IsApproved", Text = "وضعیت"},
                new SelectListItem {Value = "LikeCount", Text = "رای ها"},
                new SelectListItem {Value = "UserName", Text = "نام کاربری"},
                new SelectListItem {Value = "Author", Text = "نویسنده"},
                new SelectListItem {Value = "IP", Text = "IP"}
            };

            ViewBag.OrderByItems = new SelectList(selectListOrderBy, "Value", "Text", orderBy);


            IList<CommentDataTableModel> model = _commentService.GetDataTable(term, page, count, order, orderBy,
                searchBy);


            ViewBag.TotalRecords = (string.IsNullOrEmpty(term)) ? _commentService.Count : model.Count;


            foreach (CommentDataTableModel item in model)
            {
                item.AvatarPath = Url.Content("~/Content/Images/user.gif");
            }

            return PartialView("_DataTable", model);
        }

        [HttpGet]
        public virtual ActionResult ConfirmDelete(int id)
        {
            ViewBag.Id = id;
            return PartialView("_ConfirmDelete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Delete(int id)
        {
            _commentService.Remove(id);
            _uow.SaveChanges();
            return PartialView("_Alert", new Alert
            {
                Message = "دیدگاه مورد نظر با موفقیت حذف شد",
                Mode = AlertMode.Success
            });
        }

        [HttpGet]
        public virtual ActionResult Edit(int id)
        {
            Comment selectedComment = _commentService.GetComment(id);
            return PartialView("_Edit", new EditCommentModel
            {
                Id = selectedComment.Id,
                Body = selectedComment.Body
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Edit(EditCommentModel commentModel)
        {
            _commentService.Update(new Comment { Id = commentModel.Id, Body = commentModel.Body.ToSafeHtml() });
            _uow.SaveChanges();
            return PartialView("_Alert", new Alert
            {
                Message = "دیدگاه مورد نظر با موفقیت به روز رسانی شد",
                Mode = AlertMode.Success
            });
        }

        [HttpGet]
        public virtual ActionResult Approve(int id)
        {
            _commentService.Approve(id);
            _uow.SaveChanges();
            return RenderApproveButtons(id, "disapproved");
        }

        [HttpGet]
        public virtual ActionResult DisApprove(int id)
        {
            _commentService.DisApprove(id);
            _uow.SaveChanges();
            return RenderApproveButtons(id, "approved");
        }

        public virtual ActionResult RenderApproveButtons(int id, string type)
        {
            return ViewComponent("ApproveButtons", new {id, type});
        }

        public virtual ActionResult AutoCompleteSearch(string term, CommentSearchBy searchBy = CommentSearchBy.Body)
        {
            return new EmptyResult();
        }
    }

    public class ApproveButtonsViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(int id, string type)
        {
            ViewBag.Id = id;
            ViewBag.Status = (type == "approved") ? "approved" : "disapproved";
            return View("_ApproveStatusButton");
        }
    }
}

src/Iris.Web/Controllers/CommentController.cs
using System.Collections.Generic;
using System.Linq;
using DNTCaptcha.Core;
using Iris.Datalayer.Context;
using Iris.DomainClasses.Entities;
using Iris.Model;
using Iris.Servicelayer.Interfaces;
using Iris.Utilities;
using Iris.Utilities.DateAndTime;
using Iris.Web.Email;
using Iris.Web.Filters;
using Iris.Web.HtmlCleaner;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Language = DNTCaptcha.Core.Language;

namespace Iris.Web.Controllers
{
    public class CommentController : Controller
    {
        private readonly IArticleService _articleService;
        private readonly ICommentService _commentService;
        private readonly IOptionService _optionService;
        private readonly IPageService _pageService;
        private readonly IPostService _postService;
        private readonly IUnitOfWork _uow;
        private readonly IUserService _userService;
        private readonly IEmailService _emailService;

        public CommentController(
            IUnitOfWork uow,
            ICommentService commentService,
            IOptionService optionService,
            IPostService postService,
            IUserService userService,
            IPageService pageService,
            IArticleService articleService,
            IEmailService emailService
        )
        {
            _uow = uow;
            _commentService = commentService;
            _optionService = optionService;
            _postService = postService;
            _pageService = pageService;
            _userService = userService;
            _articleService = articleService;
            _emailService = emailService;
        }

        #region Post Comment

        [HttpGet]
        public virtual ActionResult PostComments(int id)
        {
            IList<Comment> model;
            if (User.IsInRole("admin") || User.IsInRole("moderator") || User.IsInRole("editor"))
            {
                model = _commentService.GetCommentsForPost(id);
            }
            else
            {
                model = _commentService.GetCommentsForPost(id).Where(comment => comment.IsApproved).ToList();
            }
            ViewBag.PostId = id;
            return PartialView("_PostComments", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult AddUserPostComment(AddUserCommentModel model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_AddUserPostComment", model);
            }
            var newComment = new Comment
            {
                AddedDate = DateAndTime.GetDateTime(),
                Body = model.Body.ToSafeHtml(),
                LikeCount = 0
            };

            if (model.ReplyId != null)
            {
                newComment.Parent = _uow
                    .Set<Comment>()
                    .Include(comment => comment.User)
                    .Include(comment => comment.AnonymousUser)
                    .SingleOrDefault(comment => comment.Id == model.ReplyId.Value);
            }

            newComment.User = _userService.Find(User.Identity.Name);

            bool sendData = newComment.IsApproved = !_optionService.ModeratingComment;
            newComment.Post = _postService.Find(model.Id);
            _commentService.AddComment(newComment);
            _uow.SaveChanges();


            if (model.ReplyId != null)
            {

                string toUserName;
                string toEmail;

                if (newComment.Parent.User != null)
                {
                    toUserName = newComment.Parent.User.UserName;
                    toEmail = newComment.Parent.User.Email;
                }
                else
                {
                    toUserName = newComment.Parent.AnonymousUser.Name;
                    toEmail = newComment.Parent.AnonymousUser.Email;
                }

                _emailService.SendCommentReplyNotification(new CommentReplyEmailNotificationData
                {
                    CommentId = newComment.Id,
                    CommentText = newComment.Body,
                    FromUserName = newComment.User.UserName,
                    PostId = newComment.Post.Id,
                    PostTitle = newComment.Post.Title,
                    ToUserName = toUserName,
                    ToEmail = toEmail

                }, CommentReplyType.ReplyToPostComment);
            }


            if (sendData)
            {
                return Json(new
                {
                    show = "true",
                    name = User.Identity.Name,
                    date = DateAndTime.ConvertToPersian(DateAndTime.GetDateTime()),
                    likeCount = ConvertToPersian.ConvertToPersianString(0),
                    body = model.Body
                });
            }
            return Json(new { show = "false" });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateDNTCaptcha(ErrorMessage = "تصویر امنیتی وارد شده معتبر نیست.",
            CaptchaGeneratorLanguage = Language.English,
            CaptchaGeneratorDisplayMode = DisplayMode.SumOfTwoNumbers)]
        public virtual ActionResult AddAnonymousPostComment(AddAnonymousCommentModel model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_AddAnonymousPostComment", model);
            }
            var newComment = new Comment
            {
                AddedDate = DateAndTime.GetDateTime(),
                Body = model.Body.ToSafeHtml(),
                LikeCount = 0
            };

            if (model.ReplyId != null)
            {
                newComment.Parent = _uow
                    .Set<Comment>()
                    .Include(comment => comment.User)
                    .Include(comment => comment.AnonymousUser)
                    .SingleOrDefault(comment => comment.Id == model.ReplyId.Value); ;
            }

            newComment.AnonymousUser = new AnonymousUser
            {
                Email = model.Email,
                Name = model.Name,
                IP = HttpContext.Connection.RemoteIpAddress?.ToString()
            };

            bool sendData = newComment.IsApproved = !_optionService.ModeratingComment;
            newComment.Post = _postService.Find(model.Id);
            _commentService.AddComment(newComment);
            _uow.SaveChanges();

            if (model.ReplyId != null)
            {
                _emailService.SendCommentReplyNotification(new CommentReplyEmailNotificationData
                {
                    CommentId = newComment.Id,
                    CommentText = newComment.Body,
                    FromUserName = model.Name,
                    PostId = newComment.Post.Id,
                    PostTitle = newComment.Post.Title,
                    ToUserName = newComment.Parent.User?.UserName ?? newComment.Parent.AnonymousUser.Name,
                    ToEmail = newComment.Parent.User?.Email ?? newComment.Parent.AnonymousUser.Email

                }, CommentReplyType.ReplyToPostComment);
            }

            if (sendData)
            {
                return Json(new
                {
                    show = "true",
                    name = model.Name,
                    date = DateAndTime.ConvertToPersian(DateAndTime.GetDateTime()),
                    likeCount = ConvertToPersian.ConvertToPersianString(0),
                    body = model.Body
                });
            }
            return Json(new { show = "false" });
        }

        [HttpPost("comment/addpostcomment/{id}")]
        public virtual ActionResult AddPostComment(int id, int? replyId)
        {
            if (!_postService.GetCommentStatus(id))
                return PartialView("_CommentClosed");
            ViewBag.ReplyId = replyId;
            ViewBag.PostId = id;
            return PartialView(User.Identity.IsAuthenticated
                ? "_AddUserPostComment"
                : "_AddAnonymousPostComment");
        }

        #endregion

        #region Page Comment

        [HttpGet]
        public virtual ActionResult PageComments(int id)
        {
            IList<Comment> model;
            if (User.IsInRole("admin") || User.IsInRole("moderator") || User.IsInRole("editor"))
            {
                model = _commentService.GetPageComments(id);
            }
            else
            {
                model = _commentService.GetPageComments(id, comment => comment.IsApproved).ToList();
            }
            ViewBag.PageId = id;
            return PartialView("_PageComments", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult AddUserPageComment(AddUserCommentModel model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_AddUserPageComment", model);
            }
            var newComment = new Comment
            {
                AddedDate = DateAndTime.GetDateTime(),
                Body = model.Body.ToSafeHtml(),
                LikeCount = 0,
            };

            if (model.ReplyId != null)
            {
                newComment.Parent = _uow
                    .Set<Comment>()
                    .Include(comment => comment.User)
                    .Include(comment => comment.AnonymousUser)
                    .SingleOrDefault(comment => comment.Id == model.ReplyId.Value);
            }

            newComment.User = _userService.Find(User.Identity.Name);
            newComment.Page = _pageService.Find(model.Id);
            _commentService.AddComment(newComment);
            _uow.SaveChanges();


            if (model.ReplyId != null)
            {

                string toUserName;
                string toEmail;

                if (newComment.Parent.User != null)
                {
                    toUserName = newComment.Parent.User.UserName;

src/Iris.Web/Controllers/LabelController.cs
using System.Linq;
using Iris.Servicelayer.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Iris.Web.Controllers
{
    public class LabelController : Controller
    {
        private readonly ILabelService _labelService;

        public LabelController(ILabelService labelService)
        {
            _labelService = labelService;
        }

        [Route("label/index/{id:int}/{title?}/{name?}")]
        public virtual ActionResult Index(int id, string name)
        {
            var label = _labelService.GetLabel(id);

            if (label is null)
            {
                return NotFound();
            }

            ViewBag.Id = id;
            ViewBag.Title = label.Name;

            return View();
        }

        public virtual ActionResult BooksList(int labelId, [FromBody] BooksListModel model)
        {
            return ViewComponent("BooksList", new { labelId, model.Count, model.Page });
        }
    }

    public class BooksListModel
    {
        public int Page { get; set; }
        public int Count { get; set; } = 16;
    }

    public class BooksListViewComponent : ViewComponent
    {
        private readonly IPostService _postService;

        public BooksListViewComponent(IPostService postService)
        {
            _postService = postService;
        }

        public IViewComponentResult Invoke(int labelId, int page, int count = 16)
        {
            var labelsList = _postService.GetBooksList(labelId, page, count);

            if (!labelsList.Any())
                return Content("no-more");

            return View("_BooksList", labelsList);
        }
    }
}

src/Iris.Web/Areas/Admin/Views/Comment/Copy of _DataTable.cshtml
@using Iris.Web.Helpers
@model IEnumerable<Iris.Model.AdminModel.CommentDataTableModel>
@{
    int currentPage = ViewBag.CurrentPage + 1;
    int count = ViewBag.Count;
    int max = ViewBag.TotalRecords / count;
    int firstPage = ((currentPage - 2) <= 0) ? 0 : currentPage - 3;
    int lastPage = ((currentPage + 2) >= max) ? max : currentPage + 3;
}
<div id="comment-table">
    <table style="width: 100%;" class="table iris-table">
        <thead>
            <tr>
                <td></td>
                <td>#</td>
                <td>نویسنده</td>
                <td>نظر</td>
                <td>عنوان پست</td>
                <td>تعداد رای</td>
                <td>تاریخ ارسال</td>
                <td>وضعیت</td>
                <td>عملیات</td>
            </tr>
        </thead>
        <tbody>
            @{
                var counter = ((currentPage - 1) * count) + 1;
                var IsAnnonymous = false;
            }
            @foreach (var comment in Model)
            {
                IsAnnonymous = (string.IsNullOrEmpty(comment.AuthorName)) ? false : true;
            
                <tr>
                    <td>
                        <input type="checkbox" name="PostsId" value="@comment.Id" />
                    </td>
                    <td>@Html.ConvertToPersianString(counter)</td>
                    @if (IsAnnonymous)
                    {
                        <td>@comment.AuthorName</td>
                    }
                    else
                    {
                        <td>@comment.UserName</td>
                    }
                    <td>@Html.Raw(comment.Body)</td>
                    <td>@comment.PostTitle</td>
                    <td>@Html.ConvertToPersianString(comment.LikeCount)</td>
                    <td>@Html.ConvertToPersianDateTime(Convert.ToDateTime(comment.AddDate))</td>
                    <td>
                        @if (Convert.ToBoolean(comment.IsApproved))
                        {
                            <span style="color:green">تایید شده</span>
                        }
                        else
                        {
                            <span style="color:red">تایید نشده</span>
                        }
                    </td>
                    <td>
                        @Html.ButtonDialog("ویرایش", Url.Action("Edit", "Label"), "GET", "id=" + comment.Id, "dialog", new DialogOptions { Height = "220", Width = "450", IsModal = "true", Title = "ویرایش برچسب", ShowDir = "down", ShowEffect = "drop", HideEffect = "puff", HideDir = "up" }, "btn btn-primary")
                        @Html.ButtonDialog("حذف", Url.Action("ConfirmDelete", "Label"), "GET", "id=" + comment.Id, "dialog", new DialogOptions { Height = "200", Width = "450", IsModal = "true", Title = "حذف برچسب", ShowDir = "down", ShowEffect = "explode", HideEffect = "explode" }, "btn btn-danger")
                    </td>

                </tr>
                        ++counter;
            }


        </tbody>
    </table>

    @* Page Navigation *@

    <div class="pagination pagination-centered">
        <ul>
            <li>@Html.AjaxActionLink("ابتدا", "DataTable", "Label", new { page = 0, term = ViewBag.TERM, count = ViewBag.COUNT, order = ViewBag.ORDER, orderBy = ViewBag.ORDERBY, searchBy = ViewBag.SEARCHBY }, new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, OnBegin = "showLoading", UpdateTargetId = "label-table", OnSuccess = "loadAjaxComponents", OnComplete = "hideLoading" }, null)</li>
            @for (int i = firstPage; i <= lastPage; i++)
            {
                if (i + 1 == currentPage)
                {
                <li class="active"><a href="#">@Html.ConvertToPersianString(i + 1)</a></li>
                }
                else
                {
                <li>@Html.AjaxActionLink(Html.ConvertToPersianString(i + 1).ToString(), "DataTable", "Label", new { page = i, term = ViewBag.TERM, count = ViewBag.COUNT, order = ViewBag.ORDER, orderBy = ViewBag.ORDERBY, searchBy = ViewBag.SEARCHBY }, new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, OnBegin = "showLoading", UpdateTargetId = "label-table", OnSuccess = "loadAjaxComponents", OnComplete = "hideLoading" }, null)
                </li>
                }
            }
            <li>@Html.AjaxActionLink("انتها", "DataTable", "Label", new { page = max, term = ViewBag.TERM, count = ViewBag.COUNT, order = ViewBag.ORDER, orderBy = ViewBag.ORDERBY, searchBy = ViewBag.SEARCHBY }, new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, OnBegin = "showLoading", UpdateTargetId = "label-table", OnSuccess = "loadAjaxComponents", OnComplete = "hideLoading" }, null)</li>
        </ul>
    </div>

    @* Filter Section *@

    @using (Html.AjaxBeginForm("DataTable", "Label", new AjaxOptions { UpdateTargetId = "label-table", InsertionMode = InsertionMode.Replace, HttpMethod = "POST", OnBegin = "showLoading", OnComplete = "hideLoading", OnSuccess = "loadAjaxComponents" }))
    {
        @Html.Hidden("term", ViewBag.TERM as string)
        @Html.Hidden("searchBy", ViewBag.SEARCHBY as string)
        <div class="row-fluid">
            <div class="span3">
                <span style="vertical-align: top;">نمایش به صورت</span>
                @Html.DropDownList("order", ViewBag.OrderByList as IEnumerable<SelectListItem>, new { style = "width:100px" })
            </div>
            <div class="span3">
                <span style="vertical-align: top;">بر اساس</span>
                @Html.DropDownList("orderBy", ViewBag.OrderByItems as IEnumerable<SelectListItem>, new { style = "width:120px" })
            </div>
            <div class="span3">
                <span style="vertical-align: top;">تعداد در هر صفحه</span>
                @Html.DropDownList("count", ViewBag.CountList as IEnumerable<SelectListItem>, new { style = "width:60px" })
            </div>
            <div class="span3">
                <input type="submit" name="btn-submit" value="برو" class="btn" />
            </div>
        </div>
    }

</div>

src/Iris.Web/Areas/Admin/Views/Comment/_DataTable.cshtml
@using Iris.Web
@using Iris.Web.Helpers
@using Microsoft.AspNetCore.Mvc
@using Microsoft.AspNetCore.Mvc.Rendering
@model IEnumerable<Iris.Model.AdminModel.CommentDataTableModel>
@{
    int currentPage = ViewBag.CurrentPage + 1;
    int count = ViewBag.Count;
    int max = ViewBag.TotalRecords / count;
    int firstPage = ((currentPage - 2) <= 0) ? 0 : currentPage - 3;
    int lastPage = ((currentPage + 2) >= max) ? max : currentPage + 3;
}
<div id="comment-table">
    <table style="width: 100%;" class="table iris-table">
        <thead>
            <tr>
                <td></td>
                <td>نویسنده</td>
                <td>نظر</td>
                <td>وضعیت</td>
                <td>عملیات</td>
            </tr>
        </thead>
        <tbody>
            @{
                var IsAnnonymous = false;
            }
            @foreach (var comment in Model)
            {
                IsAnnonymous = (string.IsNullOrEmpty(comment.AuthorName)) ? false : true;
            
                <tr>
                    <td style="width: 30px;">
                        <input type="checkbox" name="CommentsId" class="comments-id" value="@comment.Id" />
                    </td>
                    <td style="max-width: 80px;">
                        <div>
                            <div>
                                <img src="@comment.AvatarPath" alt="" style="width:50px;height:50px;" />
                            </div>
                            <div style="margin-top: 10px;">
                                @if (IsAnnonymous)
                                {
                                    <span>@comment.AuthorName</span>
                                    <span class="label label-info">کاربر مهمان</span>
                                }
                                else
                                {
                                    <span>@comment.UserName</span>
                                    <span class="label label-success">کاربر سایت</span>
                                }
                            </div>
                        </div>
                    </td>
                    <td style="text-align: right; max-width: 300px;">
                        <div>
                            <div>
                                <div id="sent-time">
                                    ارسال شده در:
                                    @Html.ConvertToPersianDateTime(Convert.ToDateTime(comment.AddDate), "h,t")
                                </div>
                            </div>
                            <div>
                                <div style="-ms-word-wrap: break-word; word-wrap: break-word; max-width: 500px; max-height: 100px; overflow-y: auto; border-top: solid 1px #aed5fa; border-bottom: solid 1px #aed5fa; margin: 10px 0px 10px 0px;">
                                    @comment.Body
                                </div>
                            </div>
                            <div>
                                <div style="float: right; margin-left: 100px;">
                                    در پاسخ به:
                                    @comment.PostTitle
                                </div>
                                <div style="float: right;">
                                    <span>تعداد آرا:</span>
                                    <span>@Html.ConvertToPersianString(comment.LikeCount)</span>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td id="comment-status@(comment.Id)">
                        @if (Convert.ToBoolean(comment.IsApproved))
                        {
                            @await Component.InvokeAsync("ApproveButtons"
                            , new { id = comment.Id, type = "disapproved" })
                        }
                        else
                        {
                            @await Component.InvokeAsync("ApproveButtons"
                            , new { id = comment.Id, type = "approved" })
                           
                        }

                    </td>
                    <td>
                        @Html.ButtonDialog("ویرایش", Url.Action("Edit", "Comment"), "GET", "id=" + comment.Id, "dialog", new DialogOptions { Height = "370", Width = "450", IsModal = "true", Title = "ویرایش برچسب", ShowDir = "down", ShowEffect = "drop", HideEffect = "drop", HideDir = "up" }, "btn btn-primary")
                        @Html.ButtonDialog("حذف", Url.Action("ConfirmDelete", "Comment"), "GET", "id=" + comment.Id, "dialog", new DialogOptions { Height = "200", Width = "450", IsModal = "true", Title = "حذف دیدگاه", ShowDir = "down", ShowEffect = "explode", HideEffect = "explode" }, "btn btn-danger")
                    </td>

                </tr>
            }


        </tbody>
    </table>

    @* Page Navigation *@

    <div class="pagination pagination-centered">
        <ul>
            <li>@Html.AjaxActionLink("ابتدا", "DataTable", "Comment", new { page = 0, term = ViewBag.TERM, count = ViewBag.COUNT, order = ViewBag.ORDER, orderBy = ViewBag.ORDERBY, searchBy = ViewBag.SEARCHBY }, new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, OnBegin = "showLoading", UpdateTargetId = "comment-table", OnSuccess = "loadAjaxComponents", OnComplete = "hideLoading" }, null)</li>
            @for (int i = firstPage; i <= lastPage; i++)
            {
                if (i + 1 == currentPage)
                {
                <li class="active"><a href="#">@Html.ConvertToPersianString(i + 1)</a></li>
                }
                else
                {
                <li>@Html.AjaxActionLink(Html.ConvertToPersianString(i + 1).ToString(), "DataTable", "Comment", new { page = i, term = ViewBag.TERM, count = ViewBag.COUNT, order = ViewBag.ORDER, orderBy = ViewBag.ORDERBY, searchBy = ViewBag.SEARCHBY }, new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, OnBegin = "showLoading", UpdateTargetId = "comment-table", OnSuccess = "loadAjaxComponents", OnComplete = "hideLoading" }, null)
                </li>
                }
            }
            <li>@Html.AjaxActionLink("انتها", "DataTable", "Comment", new { page = max, term = ViewBag.TERM, count = ViewBag.COUNT, order = ViewBag.ORDER, orderBy = ViewBag.ORDERBY, searchBy = ViewBag.SEARCHBY }, new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, OnBegin = "showLoading", UpdateTargetId = "comment-table", OnSuccess = "loadAjaxComponents", OnComplete = "hideLoading" }, null)</li>
        </ul>
    </div>

    @* Filter Section *@

    @using (Html.AjaxBeginForm("DataTable", "Comment", new AjaxOptions { UpdateTargetId = "comment-table", InsertionMode = InsertionMode.Replace, HttpMethod = "POST", OnBegin = "showLoading", OnComplete = "hideLoading", OnSuccess = "loadAjaxComponents" }))
    {
        @Html.Hidden("term", ViewBag.TERM as string)
        @Html.Hidden("searchBy", ViewBag.SEARCHBY as string)
        <div class="row-fluid">
            <div class="span3">
                <span style="vertical-align: top;">نمایش به صورت</span>
                @Html.DropDownList("order", ViewBag.OrderByList as IEnumerable<SelectListItem>, new { style = "width:100px" })
            </div>
            <div class="span3">
                <span style="vertical-align: top;">بر اساس</span>
                @Html.DropDownList("orderBy", ViewBag.OrderByItems as IEnumerable<SelectListItem>, new { style = "width:120px" })
            </div>
            <div class="span3">
                <span style="vertical-align: top;">تعداد در هر صفحه</span>
                @Html.DropDownList("count", ViewBag.CountList as IEnumerable<SelectListItem>, new { style = "width:60px" })
            </div>
            <div class="span3">
                <input type="submit" name="btn-submit" value="برو" class="btn" />
            </div>
        </div>
    }

</div>

src/Iris.Web/Areas/Admin/Views/Comment/_Index.cshtml
@using Iris.Web
@await Html.PartialAsync("_NavBar")
@await Html.PartialAsync("_SearchBar")
@Html.Action("DataTable", "Comment")

src/Iris.Web/Areas/Admin/Views/Comment/_NavBar.cshtml
<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="#">مدیریت دیدگاه ها</a>
        <ul class="nav">
            <li class="active"><a href="#">دیدگاه ها</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
        </ul>
    </div>
</div>