src/Iris.Web/Controllers/LabelController.cs
using System.Linq;
using Iris.Servicelayer.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Iris.Web.Controllers
{
    public class LabelController : Controller
    {
        private readonly ILabelService _labelService;

        public LabelController(ILabelService labelService)
        {
            _labelService = labelService;
        }

        [Route("label/index/{id:int}/{title?}/{name?}")]
        public virtual ActionResult Index(int id, string name)
        {
            var label = _labelService.GetLabel(id);

            if (label is null)
            {
                return NotFound();
            }

            ViewBag.Id = id;
            ViewBag.Title = label.Name;

            return View();
        }

        public virtual ActionResult BooksList(int labelId, [FromBody] BooksListModel model)
        {
            return ViewComponent("BooksList", new { labelId, model.Count, model.Page });
        }
    }

    public class BooksListModel
    {
        public int Page { get; set; }
        public int Count { get; set; } = 16;
    }

    public class BooksListViewComponent : ViewComponent
    {
        private readonly IPostService _postService;

        public BooksListViewComponent(IPostService postService)
        {
            _postService = postService;
        }

        public IViewComponentResult Invoke(int labelId, int page, int count = 16)
        {
            var labelsList = _postService.GetBooksList(labelId, page, count);

            if (!labelsList.Any())
                return Content("no-more");

            return View("_BooksList", labelsList);
        }
    }
}

src/Iris.Web/Controllers/PageController.cs
using Iris.Datalayer.Context;
using Iris.Servicelayer.Interfaces;
using Iris.Utilities;
using Iris.Web.Filters;
using Microsoft.AspNetCore.Mvc;

namespace Iris.Web.Controllers
{
    public class PageController : Controller
    {
        private readonly IPageService _pageService;
        private readonly IUnitOfWork _uow;
        private readonly IUserService _userService;

        public PageController(IUnitOfWork uow, IUserService userService, IPageService pageService)
        {
            _uow = uow;
            _userService = userService;
            _pageService = pageService;
        }

        public virtual ActionResult Index(int id)
        {
            var model = _pageService.Get(id);

            if (model == null)
            {
                return NotFound();
            }

            _pageService.IncrementVisitedCount(id);

            return View(model);
        }

        [SiteAuthorize]
        [HttpPost("page/like/{id}")]
        public virtual ActionResult Like([FromRoute] int id)
        {
            string result;
            int likeCount = 0;
            if (!_pageService.IsUserLikePage(id, User.Identity.Name))
            {
                likeCount = _pageService.Like(id, _userService.Find(User.Identity.Name));
                _uow.SaveChanges();
                result = "success";
            }
            else
            {
                result = "duplicate";
            }

            return Json(new { result, count = ConvertToPersian.ConvertToPersianString(likeCount) });
        }

        [SiteAuthorize]
        [HttpPost("page/dislike/{id}")]
        public virtual ActionResult DisLike([FromRoute] int id)
        {
            string result;
            int likeCount = 0;
            if (!_pageService.IsUserLikePage(id, User.Identity.Name))
            {
                likeCount = _pageService.DisLike(id, _userService.Find(User.Identity.Name));
                _uow.SaveChanges();
                result = "success";
            }
            else
            {
                result = "duplicate";
            }

            return Json(new { result, count = ConvertToPersian.ConvertToPersianString(likeCount) });
        }
    }
}

src/Iris.Web/Controllers/PostController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using DNTPersianUtils.Core;
using Iris.Datalayer.Context;
using Iris.DomainClasses.Entities;
using Iris.Model;
using Iris.Servicelayer.Interfaces;
using Iris.Utilities;
using Iris.Web.Filters;
using Microsoft.AspNetCore.Mvc;

namespace Iris.Web.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _postService;
        private readonly IUnitOfWork _uow;
        private readonly IUserService _userService;
        private readonly IBookSearch _bookSearch;

        public PostController(
            IUnitOfWork uow,
            IPostService postService,
            IUserService userService,
            IBookSearch bookSearch
        )
        {
            _uow = uow;
            _postService = postService;
            _userService = userService;
            _bookSearch = bookSearch;
        }

        [Route("post/index/{id:int}/{title?}")]
        public virtual ActionResult Index(int id)
        {
            var post = _postService.GetPost(id);

            if (post == null)
            {
                return NotFound();
            }

            _postService.IncrementVisitedNumber(id);

            return View(post);
        }

        [SiteAuthorize]
        [HttpPost("post/like/{id}")]
        public virtual ActionResult Like([FromRoute] int id)
        {
            string result;
            int likeCount = 0;
            if (!_postService.IsUserLikePost(id, User.Identity.Name))
            {
                likeCount = _postService.Like(id, _userService.Find(User.Identity.Name));
                _uow.SaveChanges();
                result = "success";
            }
            else
            {
                result = "duplicate";
            }

            return Json(new { result, count = ConvertToPersian.ConvertToPersianString(likeCount) });
        }

        [SiteAuthorize]
        [HttpPost("post/dislike/{id}")]
        public virtual ActionResult DisLike([FromRoute] int id)
        {
            string result;
            int likeCount = 0;
            if (!_postService.IsUserLikePost(id, User.Identity.Name))
            {
                likeCount = _postService.DisLike(id, _userService.Find(User.Identity.Name));
                _uow.SaveChanges();
                result = "success";
            }
            else
            {
                result = "duplicate";
            }

            return Json(new { result, count = ConvertToPersian.ConvertToPersianString(likeCount) });
        }

        [HttpPost("post/links")]
        public async Task<ActionResult> GetDownloadLinks(
            [FromBody] GetDownloadLinksModel model,
            CancellationToken cancellationToken
        )
        {
            if (model.Answer.Trim().ApplyCorrectYeKe() != "طهران")
            {
                return NotFound();
            }

            return PartialView("_DownloadLinks", await _postService.GetDownloadLinks(model.PostId, cancellationToken));
        }

        public virtual ActionResult SilmilarPosts(int id)
        {
            IEnumerable<MorePostsLikeThis> model = _bookSearch.GetMoreLikeThisPostItems(id);
            return PartialView("_SimilarPosts", model);
        }

        public virtual ActionResult UserPosts(string userName, int page = 0, int count = 100)
        {
            if (string.IsNullOrEmpty(userName)) userName = User.Identity.Name;

            IList<PostDetailModel> model = _postService.GetUserPosts(userName, page, count);
            ViewBag.UserName = userName;
            return PartialView("_UserPosts", model);
        }

        public virtual ActionResult UserPostsList(string userName)
        {
            ViewBag.UserName = userName;
            return View();
        }
    }

    public class GetDownloadLinksModel
    {
        public int PostId { get; set; }
        public string Answer { get; set; }
    }
}

src/Iris.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using AspNetCore.Unobtrusive.Ajax;
using DNTCaptcha.Core;
using Iris.Datalayer.Context;
using Iris.DomainClasses.Entities;
using Iris.Model;
using Iris.Servicelayer.EFServices.Enums;
using Iris.Servicelayer.Interfaces;
using Iris.Utilities.DateAndTime;
using Iris.Utilities.Security;
using Iris.Web.Filters;
using Iris.Web.Infrastructure;
using Iris.Web.IrisMembership;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

namespace Iris.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IRoleService _roleService;
        private readonly IAvatarImage _avatarImage;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IUnitOfWork _uow;
        private readonly IUserService _userService;

        public UserController(
            IUnitOfWork uow,
            IUserService userService,
            IRoleService roleService,
            IAvatarImage avatarImage,
            IWebHostEnvironment webHostEnvironment
        )
        {
            _uow = uow;
            _userService = userService;
            _roleService = roleService;
            _avatarImage = avatarImage;
            _webHostEnvironment = webHostEnvironment;
        }

        public virtual ActionResult Index(string userName)
        {
            return View(_uow.Set<User>().AsSplitQuery().Include(user => user.Role)
                .Include(user => user.UserMetaData)
                .Include(user => user.Posts)
                .Include(user => user.Pages)
                .Include(user => user.Articles)
                .Include(user => user.Comments)
                .FirstOrDefault(user => user.UserName.Equals(userName)));
        }

        [SiteAuthorize]
        public virtual ActionResult ProfilePage()
        {
            return View();
        }

        [SiteAuthorize]
        public virtual ActionResult UserDetail()
        {
            return PartialView("_UserDetail", _uow.Set<User>().Include(user => user.Role)
                .Include(user => user.UserMetaData)
                .FirstOrDefault(user => user.UserName.Equals(User.Identity.Name)));
        }

        [HttpGet]
        public virtual ActionResult LogOn(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            if (Request.IsAjaxRequest())
                return PartialView("_LogOn");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual async Task<ActionResult> LogOn(LogOnModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                if (Request.IsAjaxRequest())
                    return PartialView("_LogOn", model);
                return View(model);
            }

            string userName = string.Empty;
            int userId = 0;

            const string emailRegPattern =
                @"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$";

            string ip = HttpContext.Connection.RemoteIpAddress?.ToString();
            VerifyUserStatus verificationResult = Regex.IsMatch(model.Identity, emailRegPattern)
                ? _userService.VerifyUserByEmail(model.Identity, model.Password, ref userName, ref userId, ip)
                : _userService.VerifyUserByUserName(model.Identity, model.Password, ref userName, ref userId, ip);

            switch (verificationResult)
            {
                case VerifyUserStatus.VerifiedSuccessfully:
                    {
                        string roleOfTheUser = _roleService.GetRoleByUserId(userId).Name;

                        // set user role cookie
                        await SetAuthCookie(userName, roleOfTheUser, model.RememberMe);

                        _uow.SaveChanges();

                        if (Request.IsAjaxRequest())
                            return Content(IsValidReturnUrl(returnUrl)
                                ? string.Format("<script language='javascript' type='text/javascript'>window.location ='{0}';</script>", returnUrl)
                                : "<script language='javascript' type='text/javascript'>window.location.reload();</script>");

                        return RedirectToAction("Index", "Home");
                    }
                case VerifyUserStatus.UserIsbaned:
                    ModelState.AddModelError("", "حساب کاربری شما مسدود است");
                    break;
                default:
                    ModelState.AddModelError("", "اطلاعات وارد شده صحیح نمی باشند");
                    break;
            }
            if (Request.IsAjaxRequest())
                return PartialView("_LogOn", model);
            return View(model);
        }

        [NonAction]
        private async Task SetAuthCookie(string userName, string roleofUser, bool presistantCookie)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name,userName),
                new Claim(ClaimTypes.Role, roleofUser),
            };

            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {

                //RedirectUri = "/Home/Index",
                ExpiresUtc = DateTimeOffset.MaxValue,
                IsPersistent = presistantCookie,
                IssuedUtc = DateTimeOffset.Now
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);


            //double timeout = presistantCookie ? FormsAuthentication.Timeout.TotalMinutes : 30;

            //DateTime now = DateTime.UtcNow.ToLocalTime();
            //TimeSpan expirationTimeSapne = TimeSpan.FromMinutes(timeout);

            //var authTicket = new FormsAuthenticationTicket(
            //    1,
            //    userName,
            //    now,
            //    now.Add(expirationTimeSapne),
            //    presistantCookie,
            //    roleofUser,
            //    FormsAuthentication.FormsCookiePath
            //    );

            //string encryptedTicket = FormsAuthentication.Encrypt(authTicket);

            //var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket)
            //{
            //    HttpOnly = true,
            //    Secure = FormsAuthentication.RequireSSL,
            //    Path = FormsAuthentication.FormsCookiePath
            //};

            //if (FormsAuthentication.CookieDomain != null)
            //{
            //    authCookie.Domain = FormsAuthentication.CookieDomain;
            //}

            //if (presistantCookie)
            //    authCookie.Expires = DateTime.Now.AddMinutes(timeout);

            //Response.Cookies.Add(authCookie);

            //_formsAuthenticationService.SignIn(new User
            //{
            //    UserName = userName,
            //    Role = new Role { Name = roleofUser }
            //},
            //    presistantCookie);

        }

        [HttpGet]
        [SiteAuthorize]
        public virtual ActionResult UpdateProfile()
        {
            EditProfileModel selectedUser = _userService.GetProfileData(User.Identity.Name);

            selectedUser.AvatarPath = _avatarImage.GetAvatarImage(User.Identity.Name);

            selectedUser.AvatarStatus = _avatarImage.Exist(User.Identity.Name);

            return PartialView("_EditProfile", selectedUser);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [SiteAuthorize]
        public virtual ActionResult UpdateProfile(EditProfileModel model)
        {
            if (!ModelState.IsValid)
                return PartialView("_ValidationSummery", model);

            if (!string.IsNullOrEmpty(model.OldPassword))
            {
                if (!_userService.Authenticate(User.Identity.Name, model.OldPassword))
                    return PartialView("_Alert", new Alert
                    {
                        Message = "کلمه عبور اشتباه است",
                        Mode = AlertMode.Error
                    });
            }

            model.UserName = User.Identity.Name;
            EditedUserStatus updateResult = _userService.UpdateProfile(model);

            switch (updateResult)
            {
                case EditedUserStatus.UpdatingUserSuccessfully:
                    _uow.SaveChanges();
                    return PartialView("_Alert", new Alert
                    {
                        Message = "اطلاعات حساب کاربری با موفقیت به روز رسانی شد",
                        Mode = AlertMode.Success
                    });
                case EditedUserStatus.EmailExist:
                    return PartialView("_Alert", new Alert
                    {
                        Message = "ایمیل تکراری است",
                        Mode = AlertMode.Error
                    });
            }

            return new EmptyResult();
        }

        [HttpPost]
        [Authorize]
        public virtual ActionResult RemoveAvatar()
        {
            _avatarImage.RemoveAvatarImage(User.Identity.Name);
            return PartialView("_Alert",
                new Alert { Message = "آواتار مورد نظر با موفقیت حذف شد", Mode = AlertMode.Success });
        }

        [HttpPost]
        [Authorize]
        [AllowUploadSpecialFilesOnly(".jpg,.gif,.png")]

src/Iris.Web/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Admin Index</h2>

src/Iris.Web/Areas/Admin/Views/Home/_DashBoard.cshtml
@using Iris.Web.Helpers
@using Microsoft.AspNetCore.Mvc
@using Microsoft.AspNetCore.Mvc.Rendering
<div class="navbar navbar-inverse navbar-fixed-top" id="dashboard">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="#" style="color: white;">IRIS CMS</a>
            <div class="nav-collapse collapse">
                <ul class="nav nav-pills pull-left">@* begin User dropdown list*@
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="float: right;">@User.Identity.Name<b class="caret"></b>
                        </a>
                        <div style="float: left; width: 28px; height: 25px; margin-top: 5px;">
                            <img src="@ViewBag.AvatarPath" alt="" style="width:30px;height:30px; border-radius:2px;">
                        </div>
                        <ul class="dropdown-menu" style="min-width: 200px;">
                            <li style="padding: 10px;">
                                <img src="@ViewBag.AvatarPath" alt="" style="width:80px;height:85px; position:absolute;top:19px;right:6px; border-radius:5px;">
                            </li>
                            <li style="margin-right: 85px;"><a href="@Url.Action("ProfilePage", "User", new { area = "" })">پروفایل من</a></li>
                            <li style="margin-right: 85px;">@Html.AjaxActionLink("ویرایش شناسه من", "UpdateProfile", "User", new { area = "" }, new AjaxOptions { HttpMethod = "GET", OnSuccess = "Profile.Edit.onSuccess", LoadingElementDuration = 300, LoadingElementId = "loadingMessage" })
                            </li>
                            @using (Html.AjaxBeginForm("LogOut", "User", new { area = "" }, new AjaxOptions { HttpMethod = "POST", OnSuccess = "reloadPage", LoadingElementDuration = 300, LoadingElementId = "loadingMessage" }, new { id = "frmLogOut" }))
                            {
                                @Html.AntiForgeryToken()
                                <li style="margin-right: 85px;">
                                    <button id="btnLogOut" type="submit" style="display: none;">خروج</button>
                                    <a href="javascript:document.getElementById('btnLogOut').click()">خروج</a>
                                </li>
                            }
                        </ul>
                    </li>
                </ul>@* end User dropdown list*@
                <p class="navbar-text pull-left">درود،</p>
                @if (User.IsInRole("admin") || User.IsInRole("moderator"))
                {
                    <div class="btn-group">@* begin new dropdown list*@
                        <a class="btn dropdown-toggle btn-inverse" data-toggle="dropdown" href="#">مدیریت  <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("صفحه اصلی", "Index", "Home",new {area="Admin"})</li>
                        </ul>
                    </div>
                    <div class="btn-group">@* begin new dropdown list*@
                        <a class="btn dropdown-toggle btn-inverse" data-toggle="dropdown" href="#">سایت  <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("نمایش سایت", "Index", "Home", new { area = "" }, null)</li>
                        </ul>
                    </div>

                    <div class="btn-group">@* begin new dropdown list*@
                        <a class="btn dropdown-toggle btn-inverse" data-toggle="dropdown" href="#"><i class="icon-plus icon-white"></i>جدید  <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu">
                            <li>@Html.LinkDialog("کاربر", Url.Action("Add", "User"), "GET", null, "dialog", new DialogOptions { Height = "600", Width = "450", Title = "کاربر جدید", IsModal = "true", ShowEffect = "size", ShowDir = "down", HideEffect = "fold", HideDir = "right" })</li>

                            <li>@Html.LinkDialog("پست", Url.Action("Add", "Post"), "GET", null, "dialog", new DialogOptions { Height = "600", Width = "800", Title = "پست جدید", IsModal = "true", ShowEffect = "size", ShowDir = "down", HideEffect = "fold", HideDir = "right" })</li>

                            <li>@Html.LinkDialog("برچسب", Url.Action("Add", "Label"), "GET", null, "dialog", new DialogOptions { Height = "220", Width = "450", Title = "برچسب جدید", IsModal = "true", ShowEffect = "fade", ShowDir = "down", HideEffect = "scale", HideDir = "right" })</li>

                            <li>@Html.LinkDialog("برگه", Url.Action("Add", "Page"), "GET", null, "dialog", new DialogOptions { Height = "600", Width = "800", Title = "برگه جدید", IsModal = "true", ShowEffect = "size", ShowDir = "down", HideEffect = "clip", HideDir = "right" })</li>
                        </ul>
                    </div>
                }
@* end new dropdown list*@

            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<div id="updateProfile" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
<script type="text/javascript">
    var Profile = new Object();
    Profile.Edit = new Object();
    Profile.Edit.onSuccess = function (data) {
        $('div#updateProfile').html(data).modal('show');
    };
</script>