src/Iris.Web/Areas/Admin/Controllers/OptionController.cs
using Iris.Datalayer.Context;
using Iris.Model;
using Iris.Servicelayer.Interfaces;
using Iris.Web.Caching;
using Iris.Web.Filters;
using Microsoft.AspNetCore.Mvc;

namespace Iris.Web.Areas.Admin.Controllers
{
    [SiteAuthorize(Roles = "admin")]
    [Area("Admin")]
    public class OptionController : Controller
    {
        private readonly IOptionService _optionService;
        private readonly IUnitOfWork _uow;
        private readonly ICacheService _cacheService;

        public OptionController(IUnitOfWork uow, IOptionService optionService, ICacheService cacheService)
        {
            _uow = uow;
            _optionService = optionService;
            _cacheService = cacheService;
        }

        public virtual ActionResult Index()
        {
            return PartialView("_Index", _optionService.GetAll());
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public virtual ActionResult Index(SiteConfig model)
        {
            _optionService.Update(model);
            _uow.SaveChanges();
            _cacheService.RemoveSiteConfig();
            return PartialView("_Alert", new Alert
            {
                Message = "تنظیمات سایت با موفقیت به روز رسانی شد",
                Mode = AlertMode.Success
            });
        }
    }
}

src/Iris.Web/Areas/Admin/Views/Option/_Index.cshtml
@model Iris.Model.SiteConfig
<style>
    #frm-update-options label
    {
        width: 200px;
    }
</style>
@using (Html.AjaxBeginForm("Index", "Option", new { area = "admin" }, new AjaxOptions { UpdateTargetId = "result", InsertionMode = InsertionMode.Replace, HttpMethod = "POST", OnBegin = "showLoading", OnComplete = "hideLoading" }, new { @class = "form-horizontal", id = "frm-update-options" }))
{
    @Html.AntiForgeryToken()
    <fieldset>
        <legend>اطلاعات سایت</legend>
        <div class="control-group">
            <label class="control-label" for="SiteUrl">آدرس سایت</label>
            <div class="controls">
                @Html.TextBoxFor(op => op.SiteUrl)
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="BlogName">عنوان سایت</label>
            <div class="controls">
                @Html.TextBoxFor(op => op.BlogName)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="BlogKeywords">کلمات کلیدی</label>
            <div class="controls">
                @Html.TextBoxFor(op => op.BlogKeywords)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="BlogDescription">توضیحات</label>
            <div class="controls">
                @Html.TextBoxFor(op => op.BlogDescription)
            </div>
        </div>
    </fieldset>
    <fieldset>
        <legend>تنظیمات اطلاع رسانی</legend>
        <div class="control-group">
            <label class="control-label" for="AdminEmail">ایمیل برای اطلاع رسانی</label>
            <div class="controls">
                @Html.TextBoxFor(op => op.AdminEmail)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="CommentsNotify">اطلاع رسانی دیدگاه ها</label>
            <div class="controls">
                @Html.CheckBoxFor(op => op.CommentsNotify)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="CommentModeratingStatus">تایید نظرات پیش از نمایش</label>
            <div class="controls">
                @Html.CheckBoxFor(op => op.CommentModeratingStatus)
            </div>
        </div>
    </fieldset>
    <fieldset>
        <legend>سرور ارسال ایمیل</legend>
        <div class="control-group">
            <label class="control-label" for="MailServerUrl">سرویس دهنده ایمیل</label>
            <div class="controls">
                @Html.TextBoxFor(op => op.MailServerUrl)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="MailServerPort">درگاه</label>
            <div class="controls">
                @Html.TextBoxFor(op => op.MailServerPort)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="MailServerLogin">شناسه ورود</label>
            <div class="controls">
                @Html.TextBoxFor(op => op.MailServerLogin)
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="MailServerPass">رمز</label>
            <div class="controls">
                @Html.TextBoxFor(op => op.MailServerPass)
            </div>
        </div>
    </fieldset>
    
    <div id="result"></div>
    <input type="submit" name="btn-submit" value="ویرایش تنظیمات" class="btn btn-primary" />
}